include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors_in_immutables: false
    avoid_classes_with_only_static_members: false
    avoid_void_async: false
    sort_pub_dependencies: false
    join_return_with_assignment: false
